# Generated by Django 2.0.4 on 2018-05-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobmessageBy51',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSname', models.CharField(max_length=255)),
                ('GSlink', models.CharField(max_length=255)),
                ('ZWname', models.CharField(max_length=255)),
                ('ZWsalary', models.CharField(max_length=255)),
                ('ZWtype', models.CharField(max_length=255)),
                ('ZWexp', models.CharField(max_length=255)),
                ('ZWadd', models.CharField(max_length=255)),
                ('ZWnature', models.CharField(max_length=255)),
                ('ZDedu', models.CharField(max_length=255)),
                ('ZWnum', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('ZWinfo', models.TextField()),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobmessageByzl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSname', models.CharField(max_length=255)),
                ('GSlink', models.CharField(max_length=255)),
                ('ZWname', models.CharField(max_length=255)),
                ('ZWsalary', models.CharField(max_length=255)),
                ('ZWtype', models.CharField(max_length=255)),
                ('ZWexp', models.CharField(max_length=255)),
                ('ZWadd', models.CharField(max_length=255)),
                ('ZWnature', models.CharField(max_length=255)),
                ('ZDedu', models.CharField(max_length=255)),
                ('ZWnum', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('ZWinfo', models.TextField()),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
